### ISSUE TITLE
No WebChimera release found at the searched URL

### ISSUE THREAD

**Issue by Nextdrive-NeilChen** [Ivshti/wcjs-prebuilt#27]
I an newbie; I am sorry if I put in stupid issue report here. But this is what I got: 

whenever I ran 

> npm install wcjs-prebuilt

and these is what I got:

> wcjs-prebuilt@3.0.1 postinstall C:\Users\xxyyzz\Documents\Electron_Projects\wcjs-prebuilt
> node install.js

Fetching WebChimera prebuilt for Electron:
WebChimera version: 0.2.5
Electron version: 1.2.2
Platform: win
Arch: x64
Target dir: ./bin

Looking for WebChimera download at https://api.github.com/repos/RSATom/WebChimera.js/releases/tags/0.2.5

No WebChimera release found at the searched URL

**Comment by RSATom** [comment]
https://github.com/jaruba/node-vlcPlayer-demo/issues/11#issuecomment-228985606

it looks like `WCJS_RUNTIME_VERSION` format was changed

**Comment by RSATom** [comment]
ah, it's another problem, there are just no `WebChimera.js` prebuilt for Electron `1.2.2`

**Comment by RSATom** [comment]
yes, atm It's available for `Electron v1.2.0`
https://github.com/RSATom/WebChimera.js/releases

I'll force rebuilt for latest versions. It will be available within 30 minutes I hope.

**Comment by Nextdrive-NeilChen** [comment]
I can set to these in ENV

> WCJS_ARCH=x64
> WCJS_PLATFORM=win32
> WCJS_RUNTIME=electron
> WCJS_RUNTIME_VERSION=1.2.0
> WCJS_VERSION=0.2.5

and I still get

> wcjs-prebuilt@3.0.0 postinstall C:\Users\xxyyzz\Documents\Electron_Projects\node-vlcPlayer-demo\node_modules\wcjs-prebuilt
> node install.js

Fetching WebChimera prebuilt for Electron:
WebChimera version: 0.2.5
Electron version: 1.2.0
Platform: win
Arch: x64
Target dir: ./bin

Looking for WebChimera download at https://api.github.com/repos/RSATom/WebChimera.js/releases/tags/0.2.5

No WebChimera release found at the searched URL

so I think my Electron 1.2.2 is not the issue. 

Thank you so much for your great work!

**Comment by RSATom** [comment]
then try with
`WCJS_RUNTIME_VERSION=v1.2.0`

**Comment by guidupuy** [comment]
@RSATom is right. Cf. docs, the trailing "v" is needed.

**Comment by Nextdrive-NeilChen** [comment]
that works... sorry to have troubled you....
thank you so much

**Comment by RSATom** [comment]
@neildchen, it's ok, don't think you are last who meet this problem..

**Comment by guidupuy** [comment]
Happy to help!

**Comment by Nextdrive-NeilChen** [comment]
hello, would just like to inform you that:

https://github.com/jaruba/node-vlcPlayer-demo

where, 

Windows

set WCJS_RUNTIME=electron
set WCJS_RUNTIME_VERSION=0.37.6
set WCJS_VERSION=0.2.5
set WCJS_ARCH=ia32

there is no v there, 
maybe you can update the document when you have spare time.

thank you.

**Comment by RSATom** [comment]
I think @jaruba will fix it when will have some free time

**Comment by jaruba** [comment]
@RSATom I will, as soon as I have some time. :/

I'll need to fix at least 3 different repos as their all written the same. :(

Good catch, thanks @neildchen

**Comment by jaruba** [comment]
I updated the readme on all the repos I had with those examples.

**Comment by jaruba** [comment]
@guidupuy does `WCJS_VERSION` need a starting `v` too? (seems that way from the `wcjs-prebuilt` docs, but I was only pinged for `WCJS_RUNTIME_VERSION` in [this issue](https://github.com/jaruba/node-vlcPlayer-demo/issues/11))

**Comment by roeycohen** [comment]
i still have this error... can you try to explain better how to bypass it?
![image](https://cloud.githubusercontent.com/assets/2613845/20859737/d5047946-b96f-11e6-8694-b1659ea36b06.png)

**Comment by roeycohen** [comment]
ok, finally i found the answer.
using windows 10 64bit:
on Gruntfile.js
change vlc_libs arch to 'ia32' (line 229) - 'x64 didn't work'
change wcjs version to '0.37.6' (line 240) - an empty string from the regex didn't work.
change wcjs arch to 'ia32' (line 241) - 'x64 didn't work'.

so i'm the only windows guy here?? :)
